### PR TITLE
Header <QtDesigner/QDesignerCustomWidgetInterface> is deprecated in Qt5.5.

### PR DESCRIPTION
**Pull request by f3nix**
Use QtUiPlugin/QDesignerCustomWidgetInterface instead.

### CODE REVIEW

**Comment by IronManMark20** [comment]
Could you explain a bit more? It is deprecated in what version of Qt? We need to support a few versions.

**Comment by f3nix** [comment]
Hi,
sorry for that. I will pay more attention in the future. The minimum supported Qt5 should be Qt5.3.0? Is that right?

Regarding this pull request. I've updated the commit accordingly. This header change has been introduced in Qt5.5 (https://codereview.qt-project.org/#/c/108544/).

Cheers,
Mateusz

**Comment by ctismer** [comment]
@f3nix Qt5.3 is correct.

**Comment by f3nix** [comment]
Tested on Debian only.
GCC 4.9.2 and Qt 5.3.2
GCC 5.3.1 and Qt 5.5.1

Builds OK.

**Comment by zhihaoadsk** [comment]
I can reproduce the problem on Windows (Qt5.5, Python2.7 and VS2012) when I'm trying to enable QtUiTools stuff.
Thanks f3nix! The problem is fixed after I manually merge your changes.

**Comment by ctismer** [comment]
So I'm merging blind- and thankfully ;-)

**Pull request merged**
