### PR TITLE
Throw an exception in Qml when one happens in Python

### PR DESCRIPTION
**Pull request by empyrical**
This fixes the rather dangerous/annoying bug I discovered in #40 by throwing an exception in JS/Qml if a Python exception happens when calling a slot. Also includes tests.

This has a caveat: it requires use of private headers, as there are no public APIs currently for throwing an exception. I'm not sure if this is a huge deal, as the QtQml module already messes around with private stuff in the register type function but I'm curious if anyone has any input on this.

`signalmanager.cpp` also now goes through a CMake configure step first, so the Qml stuff can be optional.

These private functions also have the ability to throw different kinds of JS errors - I've made it so if a Python `TypeError` is raised, it'll throw a JS `TypeError` for example, same with `SyntaxError`. Others get a generic JavaScript `Error`.

### CODE REVIEW

**Comment by empyrical** [comment]
Hmm, got a few more warts to work out of this.

**Comment by empyrical** [comment]
Good to go now :)

**Comment by ctismer** [comment]
I agree that this might be not optimum. Actually not my first priority, because I want PySide2
to be ready for Maya, ASAP.

**Comment by techtonik** [comment]
>  I want PySide2 to be ready for Maya, ASAP.

Do you have a checklist for that?

**Comment by ctismer** [comment]
No, I also got no tests or sample code. They just said they will test things with their apps. There was no specification but "no new errors, no new stuff, everything that worked must work". That made little sense, because Qt5 had changed quite much...

**Comment by empyrical** [comment]
The cyclic dependency issues with Shiboken are going to be hard to solve with QtQuick<->QtQml, maybe they should be put on the backburner for this first release? Unless they said they want QML too

**Comment by ctismer** [comment]
No, I think they did not use QML, so far.

**Pull request merged**
