### PR TITLE
Adding missing QSysInfo to typesystem_core_x11

### PR DESCRIPTION
**Pull request by thopiekar**
Correct fix for failing builds on Linux

However, I wonder, whether it is possible to inherit "QSysInfo" from common and add just the specific lines for OSX and WIN. My XML skills are just good enough to copy+past this missing part.

### CODE REVIEW

**Comment by ctismer** [comment]
> However, I wonder, whether it is possible to inherit "QSysInfo" from common and add just the specific lines for OSX and WIN. My XML skills are just good enough to copy+past this missing part.

No, that is impossible. It is not related to xml, but the primitive way how the shiboken
parser works. If you double a tag, you get complaints. So the way to do conditional stuff is (unfortunately)

- rip it out of common
- adjust the needed things individually
- add them to individual files.

This XML stuff really is the source of all my headaches. For instance, you can habe things that are `since="5.5"`. But what about things that vanish some time? There is no until, you need to create a new file or something.

**Comment by thopiekar** [comment]
Don't get anything here, see:
```
[...] pyside2/build$ python
Python 2.7.10 (default, Sep 13 2015, 20:30:50) 
[GCC 5.2.1 20150911] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import PySide2.QtCore
```

**Comment by ctismer** [comment]
Yeah, ok it works. And I meant the warnings output of the build, is there something, like the warnings I suppressed?

**Comment by thopiekar** [comment]
I'm rerunning it ^^ Just a moment..

**Comment by thopiekar** [comment]
```
thopiekar@home:/media/thopiekar/91e97c17-2dbb-47e5-8804-a6f3f4501c8e/Projekte/PySide2/pyside2/build$ rm -rfv *
[...]
thopiekar@home:/media/thopiekar/91e97c17-2dbb-47e5-8804-a6f3f4501c8e/Projekte/PySide2/pyside2/build$ cmake ..
-- The C compiler identification is GNU 5.2.1
-- The CXX compiler identification is GNU 5.2.1
-- Check for working C compiler: /usr/lib/icecc/bin/cc
-- Check for working C compiler: /usr/lib/icecc/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib/icecc/bin/c++
-- Check for working CXX compiler: /usr/lib/icecc/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Shiboken2Config: Using default python: -python2.7
-- libshiboken built for Release
result:/usr/include/GL/gl.h
CMake Warning at cmake/Macros/FindQt5Extra.cmake:28 (find_package):
  By not providing "FindQt5Declarative.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5Declarative", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Declarative"
  with any of the following names:

    Qt5DeclarativeConfig.cmake
    qt5declarative-config.cmake

  Add the installation prefix of "Qt5Declarative" to CMAKE_PREFIX_PATH or set
  "Qt5Declarative_DIR" to a directory containing one of the above files.  If
  "Qt5Declarative" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:16 (include)


Qt5Core_INCLUDE_DIRS /usr/include/x86_64-linux-gnu/qt5/;/usr/include/x86_64-linux-gnu/qt5/QtCore;/usr/lib/x86_64-linux-gnu/qt5//mkspecs/linux-g++-64
-- *** computed QT_INCLUDE_DIR as /usr/include/x86_64-linux-gnu/qt5/
-- Detected OS: x11
-- PySide will be generated using the protected hack!
CMake Warning at PySide2/CMakeLists.txt:24 (find_package):
  By not providing "FindQt5Declarative.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5Declarative", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Declarative"
  with any of the following names:

    Qt5DeclarativeConfig.cmake
    qt5declarative-config.cmake

  Add the installation prefix of "Qt5Declarative" to CMAKE_PREFIX_PATH or set
  "Qt5Declarative_DIR" to a directory containing one of the above files.  If
  "Qt5Declarative" provides a separate development package or SDK, be sure it
  has been installed.


module Qt5Core found
module Qt5Concurrent found
module Qt5Gui found
module Qt5Widgets found
module Qt5PrintSupport found
module Qt5Xml found
module Qt5XmlPatterns found
module Qt5Svg found
module Qt5PrintSupport found
module Qt5Sql found
module Qt5Designer found
module Qt5UiTools found
module Qt5Test found
module Qt5Network found
module Qt5WebKit found
module Qt5WebKitWidgets found
module Qt5Script found
module Qt5ScriptTools found
module Qt5Help found
module Qt5Multimedia found
-- Checking for QAbstractPrintDialog in Qt5Widgets -- not found
-- Checking for QGtkStyle in Qt5Widgets -- not found
-- Checking for QPageSetupDialog in Qt5Widgets -- not found
-- Checking for QPrintDialog in Qt5Widgets -- not found
-- Checking for QPrintEngine in Qt5Widgets -- not found
-- Checking for QPrintPreviewDialog in Qt5Widgets -- not found
-- Checking for QPrintPreviewWidget in Qt5Widgets -- not found
-- Checking for QPrinter in Qt5Widgets -- not found
-- Checking for QPrinterInfo in Qt5Widgets -- not found
-- Checking for QSessionManager in Qt5Widgets -- not found
-- Checking for QSizeGrip in Qt5Widgets -- not found
-- Checking for QSystemTrayIcon in Qt5Widgets -- not found
-- Checking for QMacStyle in Qt5Widgets -- not found
-- Checking for QSslCertificate in QtNetwork -- not found
-- Checking for QSslCipher in QtNetwork -- not found
-- Checking for QSslConfiguration in QtNetwork -- not found
-- Checking for QSslError in QtNetwork -- not found
-- Checking for QSslKey in QtNetwork -- not found
-- Checking for QSslSocket in QtNetwork -- not found
-- QT_SRC_DIR variable not set or graphviz not found, apidoc generation targets disabled.
-- Configuring done
CMake Warning (dev) at tests/pysidetest/CMakeLists.txt:96 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "libpyside" of target "testbinding" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at tests/pysidetest/CMakeLists.txt:96 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "pyside" of target "testbinding" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /media/thopiekar/91e97c17-2dbb-47e5-8804-a6f3f4501c8e/Projekte/PySide2/pyside2/build
thopiekar@home:/media/thopiekar/91e97c17-2dbb-47e5-8804-a6f3f4501c8e/Projekte/PySide2/pyside2/build$ cd PySide2/QtCore/
thopiekar@home:/media/thopiekar/91e97c17-2dbb-47e5-8804-a6f3f4501c8e/Projekte/PySide2/pyside2/build/PySide2/QtCore$ make
[  0%] Generating moc_destroylistener.cpp
Scanning dependencies of target pyside2
[  0%] Building CXX object libpyside/CMakeFiles/pyside2.dir/dynamicqmetaobject.cpp.o
[  0%] Building CXX object libpyside/CMakeFiles/pyside2.dir/destroylistener.cpp.o                                                                                                                                   
[  5%] Building CXX object libpyside/CMakeFiles/pyside2.dir/signalmanager.cpp.o                                                                                                                                     
/media/thopiekar/91e97c17-2dbb-47e5-8804-a6f3f4501c8e/Projekte/PySide2/pyside2/libpyside/signalmanager.cpp: In member function ‘void PySide::SignalManager::addGlobalSlot(const char*, PyObject*)’:
/media/thopiekar/91e97c17-2dbb-47e5-8804-a6f3f4501c8e/Projekte/PySide2/pyside2/libpyside/signalmanager.cpp:319:5: warning: ‘int PySide::SignalManager::addGlobalSlotGetIndex(const char*, PyObject*)’ is deprecated [-Wdeprecated-declarations]                                                                                                                                                                                         
     addGlobalSlotGetIndex(slot, callback);
     ^
In file included from /media/thopiekar/91e97c17-2dbb-47e5-8804-a6f3f4501c8e/Projekte/PySide2/pyside2/libpyside/signalmanager.h:26:0,
                 from /media/thopiekar/91e97c17-2dbb-47e5-8804-a6f3f4501c8e/Projekte/PySide2/pyside2/libpyside/signalmanager.cpp:23:
/media/thopiekar/91e97c17-2dbb-47e5-8804-a6f3f4501c8e/Projekte/PySide2/pyside2/libpyside/signalmanager.h:87:27: note: declared here
     PYSIDE_DEPRECATED(int addGlobalSlotGetIndex(const char* slot, PyObject* callback));
                           ^
/media/thopiekar/91e97c17-2dbb-47e5-8804-a6f3f4501c8e/Projekte/PySide2/pyside2/libpyside/pysidemacros.h:40:41: note: in definition of macro ‘PYSIDE_DEPRECATED’
         #define PYSIDE_DEPRECATED(func) func __attribute__ ((deprecated))
                                         ^
/media/thopiekar/91e97c17-2dbb-47e5-8804-a6f3f4501c8e/Projekte/PySide2/pyside2/libpyside/signalmanager.cpp:319:41: warning: ‘int PySide::SignalManager::addGlobalSlotGetIndex(const char*, PyObject*)’ is deprecated [-Wdeprecated-declarations]                                                                                                                                                                                        
     addGlobalSlotGetIndex(slot, callback);
                                         ^
In file included from /media/thopiekar/91e97c17-2dbb-47e5-8804-a6f3f4501c8e/Projekte/PySide2/pyside2/libpyside/signalmanager.h:26:0,
                 from /media/thopiekar/91e97c17-2dbb-47e5-8804-a6f3f4501c8e/Projekte/PySide2/pyside2/libpyside/signalmanager.cpp:23:
/media/thopiekar/91e97c17-2dbb-47e5-8804-a6f3f4501c8e/Projekte/PySide2/pyside2/libpyside/signalmanager.h:87:27: note: declared here
     PYSIDE_DEPRECATED(int addGlobalSlotGetIndex(const char* slot, PyObject* callback));
                           ^
/media/thopiekar/91e97c17-2dbb-47e5-8804-a6f3f4501c8e/Projekte/PySide2/pyside2/libpyside/pysidemacros.h:40:41: note: in definition of macro ‘PYSIDE_DEPRECATED’
         #define PYSIDE_DEPRECATED(func) func __attribute__ ((deprecated))
                                         ^
[  5%] Building CXX object libpyside/CMakeFiles/pyside2.dir/globalreceiver.cpp.o
[  5%] Building CXX object libpyside/CMakeFiles/pyside2.dir/globalreceiverv2.cpp.o                                                                                                                                  
[  5%] Building CXX object libpyside/CMakeFiles/pyside2.dir/pysideclassinfo.cpp.o                                                                                                                                   
[  5%] Building CXX object libpyside/CMakeFiles/pyside2.dir/pysidemetafunction.cpp.o                                                                                                                                
[  5%] Building CXX object libpyside/CMakeFiles/pyside2.dir/pysidesignal.cpp.o                                                                                                                                      
[  5%] Building CXX object libpyside/CMakeFiles/pyside2.dir/pysideslot.cpp.o                                                                                                                                        
[ 10%] Building CXX object libpyside/CMakeFiles/pyside2.dir/pysideproperty.cpp.o                                                                                                                                    
/media/thopiekar/91e97c17-2dbb-47e5-8804-a6f3f4501c8e/Projekte/PySide2/pyside2/libpyside/pysideproperty.cpp: In function ‘void qpropertyMetaCall(PySideProperty*, PyObject*, QMetaObject::Call, void**)’:
/media/thopiekar/91e97c17-2dbb-47e5-8804-a6f3f4501c8e/Projekte/PySide2/pyside2/libpyside/pysideproperty.cpp:114:11: warning: enumeration value ‘IndexOfMethod’ not handled in switch [-Wswitch]
     switch(call) {
           ^
/media/thopiekar/91e97c17-2dbb-47e5-8804-a6f3f4501c8e/Projekte/PySide2/pyside2/libpyside/pysideproperty.cpp:114:11: warning: enumeration value ‘RegisterPropertyMetaType’ not handled in switch [-Wswitch]
/media/thopiekar/91e97c17-2dbb-47e5-8804-a6f3f4501c8e/Projekte/PySide2/pyside2/libpyside/pysideproperty.cpp:114:11: warning: enumeration value ‘RegisterMethodArgumentMetaType’ not handled in switch [-Wswitch]
[ 10%] Building CXX object libpyside/CMakeFiles/pyside2.dir/pysideqflags.cpp.o
[ 10%] Building CXX object libpyside/CMakeFiles/pyside2.dir/pysideweakref.cpp.o                                                                                                                                     
[ 10%] Building CXX object libpyside/CMakeFiles/pyside2.dir/pyside.cpp.o                                                                                                                                            
[ 10%] Building CXX object libpyside/CMakeFiles/pyside2.dir/moc_destroylistener.cpp.o                                                                                                                               
Linking CXX shared library libpyside2-python2.7.so
[ 10%] Built target pyside2
[ 10%] Running generator for QtCore...
** WARNING scope not found for function definition:QtPrivate::IsMetaTypePair<T,true>::registerConverter
        definition *ignored*
Generating class model...                    [OK]
Generating enum model...                     [OK]
Generating namespace model...                [OK]
Resolving typedefs...                        [OK]
Fixing class inheritance...                  [OK]
Detecting inconsistencies in class model...  [OK]
[OK]

Done, 0 warnings (407 known issues)
Scanning dependencies of target QtCore
[ 10%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qabstractanimation_wrapper.cpp.o
[ 10%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qabstracteventdispatcher_timerinfo_wrapper.cpp.o                                                                                     
[ 10%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qabstracteventdispatcher_wrapper.cpp.o                                                                                               
[ 15%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qabstractitemmodel_wrapper.cpp.o                                                                                                     
[ 15%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qabstractlistmodel_wrapper.cpp.o                                                                                                     
[ 15%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qabstractstate_wrapper.cpp.o                                                                                                         
[ 15%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qabstracttablemodel_wrapper.cpp.o                                                                                                    
[ 15%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qabstracttransition_wrapper.cpp.o                                                                                                    
[ 15%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qanimationgroup_wrapper.cpp.o                                                                                                        
[ 15%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qbasicmutex_wrapper.cpp.o                                                                                                            
[ 21%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qbasictimer_wrapper.cpp.o                                                                                                            
[ 21%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qbitarray_wrapper.cpp.o                                                                                                              
[ 21%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qbuffer_wrapper.cpp.o                                                                                                                
[ 21%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qbytearray_wrapper.cpp.o                                                                                                             
[ 21%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qbytearraymatcher_wrapper.cpp.o                                                                                                      
[ 21%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qchildevent_wrapper.cpp.o                                                                                                            
[ 21%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qcoreapplication_wrapper.cpp.o                                                                                                       
[ 26%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qcryptographichash_wrapper.cpp.o                                                                                                     
[ 26%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qdate_wrapper.cpp.o                                                                                                                  
[ 26%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qdatetime_wrapper.cpp.o                                                                                                              
[ 26%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qdir_wrapper.cpp.o                                                                                                                   
[ 26%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qdiriterator_wrapper.cpp.o                                                                                                           
[ 26%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qdynamicpropertychangeevent_wrapper.cpp.o                                                                                            
[ 26%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qeasingcurve_wrapper.cpp.o                                                                                                           
[ 31%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qelapsedtimer_wrapper.cpp.o                                                                                                          
[ 31%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qevent_wrapper.cpp.o                                                                                                                 
[ 31%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qeventloop_wrapper.cpp.o                                                                                                             
[ 31%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qeventtransition_wrapper.cpp.o                                                                                                       
[ 31%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qfactoryinterface_wrapper.cpp.o                                                                                                      
[ 31%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qfile_wrapper.cpp.o                                                                                                                  
[ 36%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qfiledevice_wrapper.cpp.o                                                                                                            
[ 36%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qfileinfo_wrapper.cpp.o                                                                                                              
[ 36%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qfilesystemwatcher_wrapper.cpp.o                                                                                                     
[ 36%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qfinalstate_wrapper.cpp.o                                                                                                            
[ 36%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qgenericargument_wrapper.cpp.o                                                                                                       
[ 36%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qgenericreturnargument_wrapper.cpp.o                                                                                                 
[ 36%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qhistorystate_wrapper.cpp.o                                                                                                          
[ 42%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qiodevice_wrapper.cpp.o                                                                                                              
[ 42%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qlibraryinfo_wrapper.cpp.o                                                                                                           
[ 42%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qline_wrapper.cpp.o                                                                                                                  
[ 42%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qlinef_wrapper.cpp.o                                                                                                                 
[ 42%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qlocale_wrapper.cpp.o                                                                                                                
[ 42%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qmargins_wrapper.cpp.o                                                                                                               
[ 42%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qmetaclassinfo_wrapper.cpp.o                                                                                                         
[ 47%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qmetaenum_wrapper.cpp.o                                                                                                              
[ 47%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qmetamethod_wrapper.cpp.o                                                                                                            
[ 47%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qmetaobject_connection_wrapper.cpp.o                                                                                                 
[ 47%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qmetaobject_wrapper.cpp.o                                                                                                            
[ 47%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qmetaproperty_wrapper.cpp.o                                                                                                          
[ 47%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qmimedata_wrapper.cpp.o                                                                                                              
[ 47%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qmodelindex_wrapper.cpp.o                                                                                                            
[ 52%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qmutex_wrapper.cpp.o                                                                                                                 
[ 52%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qmutexlocker_wrapper.cpp.o                                                                                                           
[ 52%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qobject_wrapper.cpp.o                                                                                                                
[ 52%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qparallelanimationgroup_wrapper.cpp.o                                                                                                
[ 52%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qpauseanimation_wrapper.cpp.o                                                                                                        
[ 52%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qpersistentmodelindex_wrapper.cpp.o                                                                                                  
[ 52%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qpluginloader_wrapper.cpp.o                                                                                                          
[ 57%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qpoint_wrapper.cpp.o
[ 57%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qpointf_wrapper.cpp.o
[ 57%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qprocess_wrapper.cpp.o
[ 57%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qprocessenvironment_wrapper.cpp.o
[ 57%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qpropertyanimation_wrapper.cpp.o
[ 57%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qreadlocker_wrapper.cpp.o
[ 63%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qreadwritelock_wrapper.cpp.o
[ 63%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qrect_wrapper.cpp.o
[ 63%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qrectf_wrapper.cpp.o
[ 63%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qregexp_wrapper.cpp.o
[ 63%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qresource_wrapper.cpp.o
[ 63%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qrunnable_wrapper.cpp.o
[ 63%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qsemaphore_wrapper.cpp.o
[ 68%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qsequentialanimationgroup_wrapper.cpp.o
[ 68%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qsettings_wrapper.cpp.o
[ 68%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qsignalmapper_wrapper.cpp.o
[ 68%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qsignaltransition_wrapper.cpp.o
[ 68%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qsize_wrapper.cpp.o
[ 68%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qsizef_wrapper.cpp.o
[ 68%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qsocketnotifier_wrapper.cpp.o
[ 73%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qstate_wrapper.cpp.o
[ 73%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qstatemachine_signalevent_wrapper.cpp.o
[ 73%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qstatemachine_wrappedevent_wrapper.cpp.o
[ 73%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qstatemachine_wrapper.cpp.o
[ 73%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qsysinfo_wrapper.cpp.o
[ 73%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qsystemsemaphore_wrapper.cpp.o
[ 73%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qt_wrapper.cpp.o
[ 78%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qtemporaryfile_wrapper.cpp.o
[ 78%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qtextboundaryfinder_wrapper.cpp.o
[ 78%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qtextcodec_converterstate_wrapper.cpp.o
[ 78%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qtextcodec_wrapper.cpp.o
[ 78%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qtextdecoder_wrapper.cpp.o
[ 78%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qtextencoder_wrapper.cpp.o
[ 78%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qtextstream_wrapper.cpp.o
[ 84%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qtextstreammanipulator_wrapper.cpp.o
[ 84%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qthread_wrapper.cpp.o
[ 84%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qthreadpool_wrapper.cpp.o
[ 84%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qtime_wrapper.cpp.o
[ 84%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qtimeline_wrapper.cpp.o
[ 84%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qtimer_wrapper.cpp.o
[ 89%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qtimerevent_wrapper.cpp.o
[ 89%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qtranslator_wrapper.cpp.o
[ 89%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qurl_wrapper.cpp.o
[ 89%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/quuid_wrapper.cpp.o
[ 89%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qvariantanimation_wrapper.cpp.o
[ 89%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qwaitcondition_wrapper.cpp.o
[ 89%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qwritelocker_wrapper.cpp.o
[ 94%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qxmlstreamattribute_wrapper.cpp.o
[ 94%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qxmlstreamattributes_wrapper.cpp.o
[ 94%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qxmlstreamentitydeclaration_wrapper.cpp.o
[ 94%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qxmlstreamentityresolver_wrapper.cpp.o
[ 94%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qxmlstreamnamespacedeclaration_wrapper.cpp.o
[ 94%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qxmlstreamnotationdeclaration_wrapper.cpp.o
[ 94%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qxmlstreamreader_wrapper.cpp.o
[100%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qxmlstreamwriter_wrapper.cpp.o
[100%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qtcore_module_wrapper.cpp.o
[100%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qdatastream_wrapper.cpp.o
[100%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/glue/qeasingcurve_glue.cpp.o
Linking CXX shared module ../QtCore.so
[100%] Built target QtCore
```

**Comment by ctismer** [comment]
about XML and shiboken: The XML is extremely limited.
If you for instance put a line break into something that is valid C++ syntax, the shiboken parser will not handle it. It is a nightmare of a hack.

**Comment by ctismer** [comment]
Great, thanks. And BTW., I think you are right and we should evict QtDeclarative (if you like to do it, do it)

**Comment by thopiekar** [comment]
Sounds like XML wasn't meant to be used for embedding code.. For future PR's just give me hint like this time, if something is wrong.

Btw. thank you for pointing it out, were to make the correct fix :smile:

**Comment by ctismer** [comment]
Oupps, what this Qt5.5 or 5.4? If 5.4, then we might see complaints in 5.5. (and yet another PR :-) )

**Comment by thopiekar** [comment]
I just browsed the Qt 5.5 docs for this addition and it says ( sorry if I'm
wrong ) that only WinVersion for WIN and MacVersion for OSX will be added
in 5.5. So there are no changes for Linux between both versions.
The build I posted was made using 5.4.

**Comment by ctismer** [comment]
Yes they claim that, but the reality is in the source. Here is what created the OSX problems: The win binary was not found.
```
#if defined(Q_OS_WIN) || defined(Q_OS_CYGWIN)
    static const WinVersion WindowsVersion;
    static WinVersion windowsVersion();
#else
    static const WinVersion WindowsVersion = WV_None;
    static WinVersion windowsVersion() { return WV_None; }
#endif
```
and I believe this could happen with Linux, too.

**Pull request merged**
